/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as sampleSol from "./sample.sol";
export type { sampleSol };
export type { Auction } from "./Auction";
